#define GAME_WIDTH 160
#define GAME_HEIGHT 144
#define SCREEN_SCALE 8
#define WINDOW_WIDTH GAME_WIDTH *SCREEN_SCALE
#define WINDOW_HEIGHT GAME_HEIGHT *SCREEN_SCALE

#define T_WIDTH 8
#define T_HEIGHT 8
